### ISSUE TITLE
Add some caching to static resources

### ISSUE THREAD

**Issue by tikiki** [WikiJourney/wikijourney_website#12]
Resources like images, banners, maybe even scripts, should be cached in the user's browser.
We can create a .htaccess to do so.

**Comment by tikiki** [comment]
.htaccess added, now almost everything is cached.
We can still add (if possible) the piwik.js script, and we have to compress HTML, CSS, and images.

**Comment by tikiki** [comment]
Oooooops... Added the .htaccess in production, we have to add it to the git repo...

**Comment by sylvainar** [comment]
I added it on the repository. Thanks !

**Comment by sylvainar** [comment]
Looks like there is still work to do.

**Comment by sylvainar** [comment]
htaccess should be written before the 2.0 to help solving #50 ( cc @tikiki )

**Comment by tikiki** [comment]
The .htaccess still works (I may give it a look to be sure), but it doesn't work on an nginx setup.

**Comment by sylvainar** [comment]
Done in #50
