### ISSUE TITLE
Utiliser des majuscules accentuées

### ISSUE THREAD

**Issue by tikiki** [WikiJourney/wikijourney_website#16]
Certains fichiers (au hasard, le fichier des types de POI) n'ont pas les majuscules accentuées.
Si on veut respecter les règles de grammaire française, il faudrait repasser un coup sur tout ça.

(Oui, cette "issue" est en français, mais le problème est franco-français, alors...)

**Comment by sylvainar** [comment]
Je m'en occupe dans la journée :)

**Comment by sylvainar** [comment]
Fixed in c9dff3a7db90c2dd17202926226a0ee214efdc80
