### ISSUE TITLE
Redirection loop with blanked referrers

### ISSUE THREAD

**Issue by kehugter** [WikiJourney/wikijourney_website#65]
Changing the site language causes an infinite redirection loop at `https://www.wikijourney.eu/action.php?lg=XX` if the referrers are blanked.

**Comment by sylvainar** [comment]
That's weird, it shouldn't happen because it's secure here : https://github.com/WikiJourney/wikijourney_website/blob/master/action.php#L43

Can you please tell me the exact steps to reproduce?

Thanks for reporting!

**Comment by kehugter** [comment]
Sure

- Start at `https://www.wikijourney.eu/index.php`, selected language is English, referres are blanked
- Go to `Languages`, select any (even English again)
- Redirection loop at `https://www.wikijourney.eu/action.php?lg=XX` with error `Error loading content (NS_ERROR_DOCUMENT_NOT_CACHED)` (no status, connection aborted). Solved immediately by allowing normal referrers

Using Firefox 40.0b1 in Debian testing.

**Comment by kehugter** [comment]
```javascript
	if (document.referrer.indexOf('action.php') === -1) {
		document.location.href = document.referrer;
	}
```

I think the error makes sense: blanked referrer will fall into this `if`, then a blank location will be assigned.

**Comment by kehugter** [comment]
`if (document.referrer && document.referrer.indexOf('action.php') === -1)`

should fix it.
